ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'POD_SUBMITTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'POD_APPROVED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'POD_REJECTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'DOCUMENTATION_READY';
