import type { DemoState } from "./types";

const today = (h: number, m = 0) => {
  const d = new Date();
  d.setHours(h, m, 0, 0);
  return d.toISOString();
};

const VLC = {
  name: "Valencia — Plataforma Puerto",
  address: "Polígono DEMO, Valencia",
  lat: 39.4699,
  lng: -0.3763,
};
const MAD = {
  name: "Madrid — Centro Nova Distribución",
  address: "Polígono DEMO, Getafe (Madrid)",
  lat: 40.3057,
  lng: -3.7329,
};

export const CARRIER_ORG = "org_tvd";
export const CUSTOMER_ORG = "org_nova";

export function createSeed(): DemoState {
  return {
    version: 1,
    organizations: [
      { id: CARRIER_ORG, name: "Transportes Valencia Demo", kind: "CARRIER", demo: true },
      { id: CUSTOMER_ORG, name: "Nova Distribución (ficticio)", kind: "SHIPPER", demo: true },
    ],
    users: [
      {
        id: "u_cust",
        name: "Laura Pérez (DEMO)",
        email: "cliente@demo.nexo.local",
        role: "CUSTOMER",
        organizationId: CUSTOMER_ORG,
      },
      {
        id: "u_admin",
        name: "Andrés Martí (DEMO)",
        email: "admin@demo.nexo.local",
        role: "TRANSPORT_ADMIN",
        organizationId: CARRIER_ORG,
      },
      {
        id: "u_disp",
        name: "Sara Ruiz (DEMO)",
        email: "trafico@demo.nexo.local",
        role: "DISPATCHER",
        organizationId: CARRIER_ORG,
      },
      {
        id: "u_ops",
        name: "Pablo Soler (DEMO)",
        email: "operaciones@demo.nexo.local",
        role: "OPERATIONS",
        organizationId: CARRIER_ORG,
      },
      {
        id: "u_acc",
        name: "Elena Vidal (DEMO)",
        email: "contabilidad@demo.nexo.local",
        role: "ACCOUNTING",
        organizationId: CARRIER_ORG,
      },
      {
        id: "u_drv",
        name: "Miguel García (DEMO)",
        email: "conductor@demo.nexo.local",
        role: "DRIVER",
        organizationId: CARRIER_ORG,
        driverId: "drv_miguel",
      },
    ],
    drivers: [
      {
        id: "drv_miguel",
        organizationId: CARRIER_ORG,
        name: "Miguel García",
        phone: "+34 600 000 001 (DEMO)",
        license: "C+E",
        status: "ACTIVO",
      },
      {
        id: "drv_ana",
        organizationId: CARRIER_ORG,
        name: "Ana Llorens",
        phone: "+34 600 000 002 (DEMO)",
        license: "C+E",
        status: "ACTIVO",
      },
      {
        id: "drv_jordi",
        organizationId: CARRIER_ORG,
        name: "Jordi Ferrer",
        phone: "+34 600 000 003 (DEMO)",
        license: "C",
        status: "DESCANSO",
      },
    ],
    vehicles: [
      {
        id: "veh_1234",
        organizationId: CARRIER_ORG,
        plate: "1234 ABC",
        type: "Tráiler frigorífico",
        reefer: true,
        status: "EN_RUTA",
      },
      {
        id: "veh_5678",
        organizationId: CARRIER_ORG,
        plate: "5678 DEF",
        type: "Lona 13,6 m",
        reefer: false,
        status: "EN_RUTA",
      },
      {
        id: "veh_9012",
        organizationId: CARRIER_ORG,
        plate: "9012 GHI",
        type: "Rígido frigorífico",
        reefer: true,
        status: "DISPONIBLE",
      },
    ],
    customers: [
      {
        id: "cus_nova",
        organizationId: CARRIER_ORG,
        customerOrgId: CUSTOMER_ORG,
        name: "Nova Distribución (ficticio)",
        contact: "Laura Pérez (DEMO)",
      },
      {
        id: "cus_other",
        organizationId: CARRIER_ORG,
        customerOrgId: "org_other",
        name: "Cliente Interno DEMO",
        contact: "—",
      },
    ],
    services: [
      {
        id: "NV-24081",
        carrierOrgId: CARRIER_ORG,
        customerOrgId: CUSTOMER_ORG,
        customerRef: "PO-NOVA-55120",
        origin: VLC,
        destination: MAD,
        cargo: "Alimentación refrigerada",
        pallets: 18,
        tempMin: 2,
        tempMax: 6,
        plannedPickup: today(6, 0),
        actualPickup: today(6, 20),
        plannedDelivery: today(11, 30),
        eta: today(11, 50),
        status: "EN_RUTA",
        assignmentConfirmed: false,
        vehicleId: "veh_1234",
        driverId: "drv_miguel",
        position: { lat: 39.86, lng: -2.0, simulated: true, at: today(9, 15) },
        progress: 0.55,
        delayed: true,
        price: 1180,
        cost: 845,
        internalNotes: "Cliente prioritario. Margen ajustado por peaje.",
        documents: [
          {
            id: "doc_cp",
            name: "Carta de porte NV-24081",
            type: "CARTA_PORTE",
            visibleToCustomer: true,
            createdAt: today(5, 50),
          },
          {
            id: "doc_deca",
            name: "DeCA / QR NV-24081",
            type: "DECA",
            visibleToCustomer: false,
            createdAt: today(5, 50),
          },
        ],
        readyToInvoice: false,
      },
      {
        id: "NV-24082",
        carrierOrgId: CARRIER_ORG,
        customerOrgId: CUSTOMER_ORG,
        customerRef: "PO-NOVA-55131",
        origin: VLC,
        destination: {
          name: "Albacete — Tienda DEMO",
          address: "Albacete",
          lat: 38.99,
          lng: -1.86,
        },
        cargo: "Bebidas",
        pallets: 12,
        plannedPickup: today(14, 0),
        plannedDelivery: today(17, 0),
        status: "ASIGNADO",
        assignmentConfirmed: true,
        vehicleId: "veh_5678",
        driverId: "drv_ana",
        progress: 0,
        delayed: false,
        price: 520,
        cost: 380,
        internalNotes: "",
        documents: [],
        readyToInvoice: false,
      },
      {
        id: "TV-11903",
        carrierOrgId: CARRIER_ORG,
        customerOrgId: "org_other",
        customerRef: "INT-0093",
        origin: { name: "Sagunto DEMO", address: "Sagunto", lat: 39.68, lng: -0.27 },
        destination: { name: "Zaragoza DEMO", address: "Zaragoza", lat: 41.65, lng: -0.88 },
        cargo: "Material de construcción",
        pallets: 22,
        plannedPickup: today(16, 0),
        plannedDelivery: today(21, 0),
        status: "PLANIFICADO",
        assignmentConfirmed: false,
        progress: 0,
        delayed: false,
        price: 890,
        cost: 640,
        internalNotes: "Pendiente de asignar vehículo.",
        documents: [],
        readyToInvoice: false,
      },
    ],
    incidents: [],
    events: [
      {
        id: "ev1",
        serviceId: "NV-24081",
        type: "CREADO",
        message: "Pedido recibido de Nova Distribución",
        actorRole: "SYSTEM",
        actorName: "Sistema",
        at: today(5, 30),
        visibility: "ALL",
      },
      {
        id: "ev2",
        serviceId: "NV-24081",
        type: "ASIGNADO",
        message: "Asignado a vehículo 1234 ABC · Miguel García",
        actorRole: "DISPATCHER",
        actorName: "Tráfico",
        at: today(5, 45),
        visibility: "ALL",
      },
      {
        id: "ev3",
        serviceId: "NV-24081",
        type: "RECOGIDA",
        message: "Carga recogida en Valencia (temperatura 4 °C)",
        actorRole: "DRIVER",
        actorName: "Miguel García",
        at: today(6, 20),
        visibility: "ALL",
      },
      {
        id: "ev4",
        serviceId: "NV-24081",
        type: "NOTA_INTERNA",
        message: "Ajustado coste por peaje AP-7",
        actorRole: "OPERATIONS",
        actorName: "Operaciones",
        at: today(7, 0),
        visibility: "INTERNAL",
      },
      {
        id: "ev5",
        serviceId: "NV-24081",
        type: "RETRASO",
        message: "ETA recalculada: +20 min por tráfico (A-3)",
        actorRole: "SYSTEM",
        actorName: "Sistema",
        at: today(9, 0),
        visibility: "ALL",
      },
    ],
    invoices: [],
    automations: [
      {
        id: "au1",
        name: "POD validado → listo para facturar",
        trigger: "POD validado",
        action: "Marcar servicio como listo para facturar y notificar a contabilidad",
        enabled: true,
      },
      {
        id: "au2",
        name: "Retraso > 15 min → aviso a cliente",
        trigger: "ETA recalculada",
        action: "Notificación en portal de cliente (simulada)",
        enabled: true,
      },
      {
        id: "au3",
        name: "Incidencia de temperatura → alerta tráfico",
        trigger: "Incidencia TEMPERATURA",
        action: "Alerta prioritaria en panel de tráfico",
        enabled: false,
      },
    ],
    integrations: [
      {
        id: "in_gmaps",
        name: "Google Maps",
        status: "SIMULADA",
        description:
          "Mapa real conectado. Las posiciones mostradas siguen siendo datos DEMO hasta integrar un proveedor de tracking.",
      },
      {
        id: "in_ges",
        name: "GES (adaptador)",
        status: "NO_CONFIGURADA",
        description: "Adaptador previsto. No se asume API disponible.",
      },
      {
        id: "in_wa",
        name: "WhatsApp / Email",
        status: "SIMULADA",
        description: "Envíos simulados. No se envía ningún mensaje real.",
      },
      {
        id: "in_ai",
        name: "Asistente IA",
        status: "SIMULADA",
        description: "Respuestas mock. Nunca modifica datos sin confirmación.",
      },
      {
        id: "in_gps",
        name: "Telemática / GPS",
        status: "PENDIENTE",
        description: "Posiciones DEMO simuladas hasta conectar proveedor.",
      },
    ],
    audit: [],
  };
}
