/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccesoRouteImport } from './routes/acceso'
import { Route as ClienteRouteImport } from './routes/cliente'
import { Route as ConductorRouteImport } from './routes/conductor'
import { Route as TransportistaRouteImport } from './routes/transportista'
import { Route as ClienteIndexRouteImport } from './routes/cliente.index'
import { Route as ClienteDocumentosRouteImport } from './routes/cliente.documentos'
import { Route as ClienteFacturacionRouteImport } from './routes/cliente.facturacion'
import { Route as ClienteIncidenciasRouteImport } from './routes/cliente.incidencias'
import { Route as ClientePedidosRouteImport } from './routes/cliente.pedidos'
import { Route as ClienteSeguimientoRouteImport } from './routes/cliente.seguimiento'
import { Route as ConductorIndexRouteImport } from './routes/conductor.index'
import { Route as ConductorIdRouteImport } from './routes/conductor.$id'
import { Route as LoginClienteRouteImport } from './routes/login.cliente'
import { Route as LoginConductorRouteImport } from './routes/login.conductor'
import { Route as LoginTransportistaRouteImport } from './routes/login.transportista'
import { Route as TransportistaIndexRouteImport } from './routes/transportista.index'
import { Route as TransportistaAutomatizacionesRouteImport } from './routes/transportista.automatizaciones'
import { Route as TransportistaClientesRouteImport } from './routes/transportista.clientes'
import { Route as TransportistaDocumentosRouteImport } from './routes/transportista.documentos'
import { Route as TransportistaFacturacionRouteImport } from './routes/transportista.facturacion'
import { Route as TransportistaFlotaRouteImport } from './routes/transportista.flota'
import { Route as TransportistaIncidenciasRouteImport } from './routes/transportista.incidencias'
import { Route as TransportistaIntegracionesRouteImport } from './routes/transportista.integraciones'
import { Route as TransportistaMapaRouteImport } from './routes/transportista.mapa'
import { Route as TransportistaPlanificacionRouteImport } from './routes/transportista.planificacion'
import { Route as TransportistaServiciosRouteImport } from './routes/transportista.servicios'
import { Route as TransportistaServiciosIndexRouteImport } from './routes/transportista.servicios.index'
import { Route as TransportistaServiciosIdRouteImport } from './routes/transportista.servicios.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccesoRoute = AccesoRouteImport.update({
  id: '/acceso',
  path: '/acceso',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteRoute = ClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const ConductorRoute = ConductorRouteImport.update({
  id: '/conductor',
  path: '/conductor',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportistaRoute = TransportistaRouteImport.update({
  id: '/transportista',
  path: '/transportista',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteIndexRoute = ClienteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClienteRoute,
} as any)
const ClienteDocumentosRoute = ClienteDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => ClienteRoute,
} as any)
const ClienteFacturacionRoute = ClienteFacturacionRouteImport.update({
  id: '/facturacion',
  path: '/facturacion',
  getParentRoute: () => ClienteRoute,
} as any)
const ClienteIncidenciasRoute = ClienteIncidenciasRouteImport.update({
  id: '/incidencias',
  path: '/incidencias',
  getParentRoute: () => ClienteRoute,
} as any)
const ClientePedidosRoute = ClientePedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => ClienteRoute,
} as any)
const ClienteSeguimientoRoute = ClienteSeguimientoRouteImport.update({
  id: '/seguimiento',
  path: '/seguimiento',
  getParentRoute: () => ClienteRoute,
} as any)
const ConductorIndexRoute = ConductorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConductorRoute,
} as any)
const ConductorIdRoute = ConductorIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ConductorRoute,
} as any)
const LoginClienteRoute = LoginClienteRouteImport.update({
  id: '/login/cliente',
  path: '/login/cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginConductorRoute = LoginConductorRouteImport.update({
  id: '/login/conductor',
  path: '/login/conductor',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginTransportistaRoute = LoginTransportistaRouteImport.update({
  id: '/login/transportista',
  path: '/login/transportista',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportistaIndexRoute = TransportistaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TransportistaRoute,
} as any)
const TransportistaAutomatizacionesRoute =
  TransportistaAutomatizacionesRouteImport.update({
    id: '/automatizaciones',
    path: '/automatizaciones',
    getParentRoute: () => TransportistaRoute,
  } as any)
const TransportistaClientesRoute = TransportistaClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => TransportistaRoute,
} as any)
const TransportistaDocumentosRoute = TransportistaDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => TransportistaRoute,
} as any)
const TransportistaFacturacionRoute =
  TransportistaFacturacionRouteImport.update({
    id: '/facturacion',
    path: '/facturacion',
    getParentRoute: () => TransportistaRoute,
  } as any)
const TransportistaFlotaRoute = TransportistaFlotaRouteImport.update({
  id: '/flota',
  path: '/flota',
  getParentRoute: () => TransportistaRoute,
} as any)
const TransportistaIncidenciasRoute =
  TransportistaIncidenciasRouteImport.update({
    id: '/incidencias',
    path: '/incidencias',
    getParentRoute: () => TransportistaRoute,
  } as any)
const TransportistaIntegracionesRoute =
  TransportistaIntegracionesRouteImport.update({
    id: '/integraciones',
    path: '/integraciones',
    getParentRoute: () => TransportistaRoute,
  } as any)
const TransportistaMapaRoute = TransportistaMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => TransportistaRoute,
} as any)
const TransportistaPlanificacionRoute =
  TransportistaPlanificacionRouteImport.update({
    id: '/planificacion',
    path: '/planificacion',
    getParentRoute: () => TransportistaRoute,
  } as any)
const TransportistaServiciosRoute = TransportistaServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => TransportistaRoute,
} as any)
const TransportistaServiciosIndexRoute =
  TransportistaServiciosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TransportistaServiciosRoute,
  } as any)
const TransportistaServiciosIdRoute =
  TransportistaServiciosIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => TransportistaServiciosRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acceso': typeof AccesoRoute
  '/cliente': typeof ClienteRouteWithChildren
  '/conductor': typeof ConductorRouteWithChildren
  '/transportista': typeof TransportistaRouteWithChildren
  '/cliente/documentos': typeof ClienteDocumentosRoute
  '/cliente/facturacion': typeof ClienteFacturacionRoute
  '/cliente/incidencias': typeof ClienteIncidenciasRoute
  '/cliente/pedidos': typeof ClientePedidosRoute
  '/cliente/seguimiento': typeof ClienteSeguimientoRoute
  '/conductor/$id': typeof ConductorIdRoute
  '/login/cliente': typeof LoginClienteRoute
  '/login/conductor': typeof LoginConductorRoute
  '/login/transportista': typeof LoginTransportistaRoute
  '/transportista/automatizaciones': typeof TransportistaAutomatizacionesRoute
  '/transportista/clientes': typeof TransportistaClientesRoute
  '/transportista/documentos': typeof TransportistaDocumentosRoute
  '/transportista/facturacion': typeof TransportistaFacturacionRoute
  '/transportista/flota': typeof TransportistaFlotaRoute
  '/transportista/incidencias': typeof TransportistaIncidenciasRoute
  '/transportista/integraciones': typeof TransportistaIntegracionesRoute
  '/transportista/mapa': typeof TransportistaMapaRoute
  '/transportista/planificacion': typeof TransportistaPlanificacionRoute
  '/transportista/servicios': typeof TransportistaServiciosRouteWithChildren
  '/cliente/': typeof ClienteIndexRoute
  '/conductor/': typeof ConductorIndexRoute
  '/transportista/': typeof TransportistaIndexRoute
  '/transportista/servicios/$id': typeof TransportistaServiciosIdRoute
  '/transportista/servicios/': typeof TransportistaServiciosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acceso': typeof AccesoRoute
  '/cliente/documentos': typeof ClienteDocumentosRoute
  '/cliente/facturacion': typeof ClienteFacturacionRoute
  '/cliente/incidencias': typeof ClienteIncidenciasRoute
  '/cliente/pedidos': typeof ClientePedidosRoute
  '/cliente/seguimiento': typeof ClienteSeguimientoRoute
  '/conductor/$id': typeof ConductorIdRoute
  '/login/cliente': typeof LoginClienteRoute
  '/login/conductor': typeof LoginConductorRoute
  '/login/transportista': typeof LoginTransportistaRoute
  '/transportista/automatizaciones': typeof TransportistaAutomatizacionesRoute
  '/transportista/clientes': typeof TransportistaClientesRoute
  '/transportista/documentos': typeof TransportistaDocumentosRoute
  '/transportista/facturacion': typeof TransportistaFacturacionRoute
  '/transportista/flota': typeof TransportistaFlotaRoute
  '/transportista/incidencias': typeof TransportistaIncidenciasRoute
  '/transportista/integraciones': typeof TransportistaIntegracionesRoute
  '/transportista/mapa': typeof TransportistaMapaRoute
  '/transportista/planificacion': typeof TransportistaPlanificacionRoute
  '/cliente': typeof ClienteIndexRoute
  '/conductor': typeof ConductorIndexRoute
  '/transportista': typeof TransportistaIndexRoute
  '/transportista/servicios/$id': typeof TransportistaServiciosIdRoute
  '/transportista/servicios': typeof TransportistaServiciosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acceso': typeof AccesoRoute
  '/cliente': typeof ClienteRouteWithChildren
  '/conductor': typeof ConductorRouteWithChildren
  '/transportista': typeof TransportistaRouteWithChildren
  '/cliente/documentos': typeof ClienteDocumentosRoute
  '/cliente/facturacion': typeof ClienteFacturacionRoute
  '/cliente/incidencias': typeof ClienteIncidenciasRoute
  '/cliente/pedidos': typeof ClientePedidosRoute
  '/cliente/seguimiento': typeof ClienteSeguimientoRoute
  '/conductor/$id': typeof ConductorIdRoute
  '/login/cliente': typeof LoginClienteRoute
  '/login/conductor': typeof LoginConductorRoute
  '/login/transportista': typeof LoginTransportistaRoute
  '/transportista/automatizaciones': typeof TransportistaAutomatizacionesRoute
  '/transportista/clientes': typeof TransportistaClientesRoute
  '/transportista/documentos': typeof TransportistaDocumentosRoute
  '/transportista/facturacion': typeof TransportistaFacturacionRoute
  '/transportista/flota': typeof TransportistaFlotaRoute
  '/transportista/incidencias': typeof TransportistaIncidenciasRoute
  '/transportista/integraciones': typeof TransportistaIntegracionesRoute
  '/transportista/mapa': typeof TransportistaMapaRoute
  '/transportista/planificacion': typeof TransportistaPlanificacionRoute
  '/transportista/servicios': typeof TransportistaServiciosRouteWithChildren
  '/cliente/': typeof ClienteIndexRoute
  '/conductor/': typeof ConductorIndexRoute
  '/transportista/': typeof TransportistaIndexRoute
  '/transportista/servicios/$id': typeof TransportistaServiciosIdRoute
  '/transportista/servicios/': typeof TransportistaServiciosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acceso'
    | '/cliente'
    | '/conductor'
    | '/transportista'
    | '/cliente/documentos'
    | '/cliente/facturacion'
    | '/cliente/incidencias'
    | '/cliente/pedidos'
    | '/cliente/seguimiento'
    | '/conductor/$id'
    | '/login/cliente'
    | '/login/conductor'
    | '/login/transportista'
    | '/transportista/automatizaciones'
    | '/transportista/clientes'
    | '/transportista/documentos'
    | '/transportista/facturacion'
    | '/transportista/flota'
    | '/transportista/incidencias'
    | '/transportista/integraciones'
    | '/transportista/mapa'
    | '/transportista/planificacion'
    | '/transportista/servicios'
    | '/cliente/'
    | '/conductor/'
    | '/transportista/'
    | '/transportista/servicios/$id'
    | '/transportista/servicios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acceso'
    | '/cliente/documentos'
    | '/cliente/facturacion'
    | '/cliente/incidencias'
    | '/cliente/pedidos'
    | '/cliente/seguimiento'
    | '/conductor/$id'
    | '/login/cliente'
    | '/login/conductor'
    | '/login/transportista'
    | '/transportista/automatizaciones'
    | '/transportista/clientes'
    | '/transportista/documentos'
    | '/transportista/facturacion'
    | '/transportista/flota'
    | '/transportista/incidencias'
    | '/transportista/integraciones'
    | '/transportista/mapa'
    | '/transportista/planificacion'
    | '/cliente'
    | '/conductor'
    | '/transportista'
    | '/transportista/servicios/$id'
    | '/transportista/servicios'
  id:
    | '__root__'
    | '/'
    | '/acceso'
    | '/cliente'
    | '/conductor'
    | '/transportista'
    | '/cliente/documentos'
    | '/cliente/facturacion'
    | '/cliente/incidencias'
    | '/cliente/pedidos'
    | '/cliente/seguimiento'
    | '/conductor/$id'
    | '/login/cliente'
    | '/login/conductor'
    | '/login/transportista'
    | '/transportista/automatizaciones'
    | '/transportista/clientes'
    | '/transportista/documentos'
    | '/transportista/facturacion'
    | '/transportista/flota'
    | '/transportista/incidencias'
    | '/transportista/integraciones'
    | '/transportista/mapa'
    | '/transportista/planificacion'
    | '/transportista/servicios'
    | '/cliente/'
    | '/conductor/'
    | '/transportista/'
    | '/transportista/servicios/$id'
    | '/transportista/servicios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccesoRoute: typeof AccesoRoute
  ClienteRoute: typeof ClienteRouteWithChildren
  ConductorRoute: typeof ConductorRouteWithChildren
  TransportistaRoute: typeof TransportistaRouteWithChildren
  LoginClienteRoute: typeof LoginClienteRoute
  LoginConductorRoute: typeof LoginConductorRoute
  LoginTransportistaRoute: typeof LoginTransportistaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acceso': {
      id: '/acceso'
      path: '/acceso'
      fullPath: '/acceso'
      preLoaderRoute: typeof AccesoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente': {
      id: '/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof ClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conductor': {
      id: '/conductor'
      path: '/conductor'
      fullPath: '/conductor'
      preLoaderRoute: typeof ConductorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transportista': {
      id: '/transportista'
      path: '/transportista'
      fullPath: '/transportista'
      preLoaderRoute: typeof TransportistaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente/': {
      id: '/cliente/'
      path: '/'
      fullPath: '/cliente/'
      preLoaderRoute: typeof ClienteIndexRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/cliente/documentos': {
      id: '/cliente/documentos'
      path: '/documentos'
      fullPath: '/cliente/documentos'
      preLoaderRoute: typeof ClienteDocumentosRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/cliente/facturacion': {
      id: '/cliente/facturacion'
      path: '/facturacion'
      fullPath: '/cliente/facturacion'
      preLoaderRoute: typeof ClienteFacturacionRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/cliente/incidencias': {
      id: '/cliente/incidencias'
      path: '/incidencias'
      fullPath: '/cliente/incidencias'
      preLoaderRoute: typeof ClienteIncidenciasRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/cliente/pedidos': {
      id: '/cliente/pedidos'
      path: '/pedidos'
      fullPath: '/cliente/pedidos'
      preLoaderRoute: typeof ClientePedidosRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/cliente/seguimiento': {
      id: '/cliente/seguimiento'
      path: '/seguimiento'
      fullPath: '/cliente/seguimiento'
      preLoaderRoute: typeof ClienteSeguimientoRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/conductor/': {
      id: '/conductor/'
      path: '/'
      fullPath: '/conductor/'
      preLoaderRoute: typeof ConductorIndexRouteImport
      parentRoute: typeof ConductorRoute
    }
    '/conductor/$id': {
      id: '/conductor/$id'
      path: '/$id'
      fullPath: '/conductor/$id'
      preLoaderRoute: typeof ConductorIdRouteImport
      parentRoute: typeof ConductorRoute
    }
    '/login/cliente': {
      id: '/login/cliente'
      path: '/login/cliente'
      fullPath: '/login/cliente'
      preLoaderRoute: typeof LoginClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/conductor': {
      id: '/login/conductor'
      path: '/login/conductor'
      fullPath: '/login/conductor'
      preLoaderRoute: typeof LoginConductorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/transportista': {
      id: '/login/transportista'
      path: '/login/transportista'
      fullPath: '/login/transportista'
      preLoaderRoute: typeof LoginTransportistaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transportista/': {
      id: '/transportista/'
      path: '/'
      fullPath: '/transportista/'
      preLoaderRoute: typeof TransportistaIndexRouteImport
      parentRoute: typeof TransportistaRoute
    }
    '/transportista/automatizaciones': {
      id: '/transportista/automatizaciones'
      path: '/automatizaciones'
      fullPath: '/transportista/automatizaciones'
      preLoaderRoute: typeof TransportistaAutomatizacionesRouteImport
      parentRoute: typeof TransportistaRoute
    }
    '/transportista/clientes': {
      id: '/transportista/clientes'
      path: '/clientes'
      fullPath: '/transportista/clientes'
      preLoaderRoute: typeof TransportistaClientesRouteImport
      parentRoute: typeof TransportistaRoute
    }
    '/transportista/documentos': {
      id: '/transportista/documentos'
      path: '/documentos'
      fullPath: '/transportista/documentos'
      preLoaderRoute: typeof TransportistaDocumentosRouteImport
      parentRoute: typeof TransportistaRoute
    }
    '/transportista/facturacion': {
      id: '/transportista/facturacion'
      path: '/facturacion'
      fullPath: '/transportista/facturacion'
      preLoaderRoute: typeof TransportistaFacturacionRouteImport
      parentRoute: typeof TransportistaRoute
    }
    '/transportista/flota': {
      id: '/transportista/flota'
      path: '/flota'
      fullPath: '/transportista/flota'
      preLoaderRoute: typeof TransportistaFlotaRouteImport
      parentRoute: typeof TransportistaRoute
    }
    '/transportista/incidencias': {
      id: '/transportista/incidencias'
      path: '/incidencias'
      fullPath: '/transportista/incidencias'
      preLoaderRoute: typeof TransportistaIncidenciasRouteImport
      parentRoute: typeof TransportistaRoute
    }
    '/transportista/integraciones': {
      id: '/transportista/integraciones'
      path: '/integraciones'
      fullPath: '/transportista/integraciones'
      preLoaderRoute: typeof TransportistaIntegracionesRouteImport
      parentRoute: typeof TransportistaRoute
    }
    '/transportista/mapa': {
      id: '/transportista/mapa'
      path: '/mapa'
      fullPath: '/transportista/mapa'
      preLoaderRoute: typeof TransportistaMapaRouteImport
      parentRoute: typeof TransportistaRoute
    }
    '/transportista/planificacion': {
      id: '/transportista/planificacion'
      path: '/planificacion'
      fullPath: '/transportista/planificacion'
      preLoaderRoute: typeof TransportistaPlanificacionRouteImport
      parentRoute: typeof TransportistaRoute
    }
    '/transportista/servicios': {
      id: '/transportista/servicios'
      path: '/servicios'
      fullPath: '/transportista/servicios'
      preLoaderRoute: typeof TransportistaServiciosRouteImport
      parentRoute: typeof TransportistaRoute
    }
    '/transportista/servicios/': {
      id: '/transportista/servicios/'
      path: '/'
      fullPath: '/transportista/servicios/'
      preLoaderRoute: typeof TransportistaServiciosIndexRouteImport
      parentRoute: typeof TransportistaServiciosRoute
    }
    '/transportista/servicios/$id': {
      id: '/transportista/servicios/$id'
      path: '/$id'
      fullPath: '/transportista/servicios/$id'
      preLoaderRoute: typeof TransportistaServiciosIdRouteImport
      parentRoute: typeof TransportistaServiciosRoute
    }
  }
}

interface ClienteRouteChildren {
  ClienteDocumentosRoute: typeof ClienteDocumentosRoute
  ClienteFacturacionRoute: typeof ClienteFacturacionRoute
  ClienteIncidenciasRoute: typeof ClienteIncidenciasRoute
  ClientePedidosRoute: typeof ClientePedidosRoute
  ClienteSeguimientoRoute: typeof ClienteSeguimientoRoute
  ClienteIndexRoute: typeof ClienteIndexRoute
}

const ClienteRouteChildren: ClienteRouteChildren = {
  ClienteDocumentosRoute: ClienteDocumentosRoute,
  ClienteFacturacionRoute: ClienteFacturacionRoute,
  ClienteIncidenciasRoute: ClienteIncidenciasRoute,
  ClientePedidosRoute: ClientePedidosRoute,
  ClienteSeguimientoRoute: ClienteSeguimientoRoute,
  ClienteIndexRoute: ClienteIndexRoute,
}

const ClienteRouteWithChildren =
  ClienteRoute._addFileChildren(ClienteRouteChildren)

interface ConductorRouteChildren {
  ConductorIdRoute: typeof ConductorIdRoute
  ConductorIndexRoute: typeof ConductorIndexRoute
}

const ConductorRouteChildren: ConductorRouteChildren = {
  ConductorIdRoute: ConductorIdRoute,
  ConductorIndexRoute: ConductorIndexRoute,
}

const ConductorRouteWithChildren = ConductorRoute._addFileChildren(
  ConductorRouteChildren,
)

interface TransportistaServiciosRouteChildren {
  TransportistaServiciosIdRoute: typeof TransportistaServiciosIdRoute
  TransportistaServiciosIndexRoute: typeof TransportistaServiciosIndexRoute
}

const TransportistaServiciosRouteChildren: TransportistaServiciosRouteChildren =
  {
    TransportistaServiciosIdRoute: TransportistaServiciosIdRoute,
    TransportistaServiciosIndexRoute: TransportistaServiciosIndexRoute,
  }

const TransportistaServiciosRouteWithChildren =
  TransportistaServiciosRoute._addFileChildren(
    TransportistaServiciosRouteChildren,
  )

interface TransportistaRouteChildren {
  TransportistaAutomatizacionesRoute: typeof TransportistaAutomatizacionesRoute
  TransportistaClientesRoute: typeof TransportistaClientesRoute
  TransportistaDocumentosRoute: typeof TransportistaDocumentosRoute
  TransportistaFacturacionRoute: typeof TransportistaFacturacionRoute
  TransportistaFlotaRoute: typeof TransportistaFlotaRoute
  TransportistaIncidenciasRoute: typeof TransportistaIncidenciasRoute
  TransportistaIntegracionesRoute: typeof TransportistaIntegracionesRoute
  TransportistaMapaRoute: typeof TransportistaMapaRoute
  TransportistaPlanificacionRoute: typeof TransportistaPlanificacionRoute
  TransportistaServiciosRoute: typeof TransportistaServiciosRouteWithChildren
  TransportistaIndexRoute: typeof TransportistaIndexRoute
}

const TransportistaRouteChildren: TransportistaRouteChildren = {
  TransportistaAutomatizacionesRoute: TransportistaAutomatizacionesRoute,
  TransportistaClientesRoute: TransportistaClientesRoute,
  TransportistaDocumentosRoute: TransportistaDocumentosRoute,
  TransportistaFacturacionRoute: TransportistaFacturacionRoute,
  TransportistaFlotaRoute: TransportistaFlotaRoute,
  TransportistaIncidenciasRoute: TransportistaIncidenciasRoute,
  TransportistaIntegracionesRoute: TransportistaIntegracionesRoute,
  TransportistaMapaRoute: TransportistaMapaRoute,
  TransportistaPlanificacionRoute: TransportistaPlanificacionRoute,
  TransportistaServiciosRoute: TransportistaServiciosRouteWithChildren,
  TransportistaIndexRoute: TransportistaIndexRoute,
}

const TransportistaRouteWithChildren = TransportistaRoute._addFileChildren(
  TransportistaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccesoRoute: AccesoRoute,
  ClienteRoute: ClienteRouteWithChildren,
  ConductorRoute: ConductorRouteWithChildren,
  TransportistaRoute: TransportistaRouteWithChildren,
  LoginClienteRoute: LoginClienteRoute,
  LoginConductorRoute: LoginConductorRoute,
  LoginTransportistaRoute: LoginTransportistaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
